{% set version = "4.19.3" %}

package:
  name: sip
  version: {{ version }}

source:
  fn:   sip-{{ version }}.tar.gz  # [unix]
  url:  http://sourceforge.net/projects/pyqt/files/sip/sip-{{ version }}/sip-{{ version }}.tar.gz  # [unix]
  sha256: 740df844f80cc45dcc9b23294a92492923bc403ce88e68c35783f27c177c4b74  # [unix]
  fn:   sip-{{ version }}.zip  # [win]
  url:  http://sourceforge.net/projects/pyqt/files/sip/sip-{{ version }}/sip-{{ version }}.zip  # [win]
  sha256: ed3bf946cff8895bdf26f36d08cfc1d3f2f06ad7298b6a2d7137ca9df2c9729f  # [win]

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - sip
  files:
    - test

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL-3.0
  license_file: LICENSE
  summary: Create Python bindings for C and C++ libraries
  description: |
    SIP is a tool that makes it very easy to create Python bindings for C and
    C++ libraries. SIP comprises a code generator and a Python module. The
    code generator processes a set of specification files and generates C or
    C++ code which is then compiled to create the bindings extension module.
    The SIP Python module provides support functions to the automatically
    generated code.
  doc_url: http://pyqt.sourceforge.net/Docs/sip4/
  dev_url: https://github.com/ifwe/sip

extra:
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
