{% set name = "sip" %}
{% set version = "6.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sip-{{ version }}.tar.gz
  sha256: 7fc959e48e6ec5d5af8bd026f69f5e24d08b3cb8abb342176f5ab8030cc07d7a

build:
  skip: true  # [py<38]
  entry_points:
    - sip-distinfo = sipbuild.tools.distinfo:main
    - sip-module = sipbuild.tools.module:main
    - sip-build = sipbuild.tools.build:main
    - sip-install = sipbuild.tools.install:main
    - sip-sdist = sipbuild.tools.sdist:main
    - sip-wheel = sipbuild.tools.wheel:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8
    - packaging
    - setuptools
    - tomli  # [py<311]

test:
  imports:
    - sip
  commands:
    - pip check
    - sip-distinfo --help
    - sip-module --help
    - sip-build --help
    - sip-install --help
    - sip-sdist --help
    - sip-wheel --help
  requires:
    - pip

about:
  summary: A Python bindings generator for C/C++ libraries
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - sipbuild/module/source/13/LICENSE
    - sipbuild/module/source/12/LICENSE

extra:
  anaconda-services:
    reason: Dependency for pyqt6
    recipe-maintainers:
      - ianaobi
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - mingwandroid
    - msarahan
    - ocefpaf

