{% set name = "sip" %}
{% set version = "6.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sip-{{ version }}.tar.gz
  sha256: 083ced94f85315493231119a63970b2ba42b1d38b38e730a70e02a99191a89c6

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('sip', max_pin='x.x') }}
  entry_points:
    - sip-distinfo = sipbuild.tools.distinfo:main
    - sip-module = sipbuild.tools.module:main
    - sip-build = sipbuild.tools.build:main
    - sip-install = sipbuild.tools.install:main
    - sip-sdist = sipbuild.tools.sdist:main
    - sip-wheel = sipbuild.tools.wheel:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=77
    - setuptools_scm >=8
  run:
    - python
    - packaging >=24.2
    - setuptools >=75.8.1
    - tomli  # [py<311]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - pip
  imports:
    - sipbuild
    - sipbuild.distinfo
    - sipbuild.generator
    - sipbuild.module
    - sipbuild.tools
  files:
    - test
  commands:
    - pip check
    # make sure the version reported by pip is correct
    - "pip show {{ name }} | grep -Fx 'Version: {{ version }}'"  # [not win]
    - sip-distinfo --help
    - sip-module --help
    - sip-build --help
    - sip-install --help
    - sip-sdist --help
    - sip-wheel --help

about:
  home: https://pypi.org/project/sip/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python bindings generator for C and C++ libraries
  description: |
    SIP is a collection of tools that makes it very easy to create Python bindings for C and C++ libraries. It was
    originally developed in 1998 to create PyQt, the Python bindings for the Qt toolkit, but can be used to create
    bindings for any C or C++ library. For example it is also used to generate wxPython, the Python bindings for
    wxWidgets.
  doc_url: https://python-sip.readthedocs.io
  dev_url: https://github.com/Python-SIP/sip

extra:
  skip-lints:
    - python_build_tool_in_run
    - has_run_test_and_commands
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - mingwandroid
    - msarahan
    - ocefpaf
