{% set name = "sip" %}
{% set version = "6.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sip-{{ version }}.tar.gz
  sha256: fa0515697d4c98dbe04d9e898d816de1427e5b9ae5d0e152169109fd21f5d29c

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('sip', max_pin='x.x') }}
  entry_points:
    - sip-distinfo = sipbuild.tools.distinfo:main
    - sip-module = sipbuild.tools.module:main
    - sip-build = sipbuild.tools.build:main
    - sip-install = sipbuild.tools.install:main
    - sip-sdist = sipbuild.tools.sdist:main
    - sip-wheel = sipbuild.tools.wheel:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - packaging
    - setuptools >=69.5
    - tomli  # [py<311]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - pip
  imports:
    - sipbuild
    - sipbuild.distinfo
    - sipbuild.generator
    - sipbuild.module
    - sipbuild.tools
  files:
    - test

about:
  home: https://pypi.org/project/sip/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python bindings generator for C and C++ libraries
  description: |
    SIP is a collection of tools that makes it very easy to create Python bindings for C and C++ libraries. It was
    originally developed in 1998 to create PyQt, the Python bindings for the Qt toolkit, but can be used to create
    bindings for any C or C++ library. For example it is also used to generate wxPython, the Python bindings for
    wxWidgets.
  doc_url: https://python-sip.readthedocs.io
  dev_url: https://github.com/Python-SIP/sip

extra:
  skip-lints:
    - python_build_tool_in_run
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - mingwandroid
    - msarahan
    - ocefpaf
