travis:
  secure:
    BINSTAR_TOKEN: uC+TwTP+L3xjQSDkZbFgWxl8Rhl/xYVmkzpUwQy5FaZw9HZcGNmgOTlMlRhsb/LxsbkHl5mKiCDwIYL2/8Vpkn24ry5OVcvlGipLkPbdt3EJv8YLA3pjsBv8duJYWFg4wz4HBlrlbwiAGTpeGmro48g7g21VucYCEScPM7EUId4jAIZgWHnIM8NpxY7dnnIWxQnNn9dR8Fv5CTmZJp1uMkzJvF6GNwo6sTdXItEbR68iE+OPbJPn4MaSs+UzbK4dteUKnN1Mf/9EmN27dodYVdkAMycIbDbU7TFA2LZike+TQYi0ddJRzBzq+Na39XS0vJJ+V0hP4IMi5R+RFBrNUAweX8b2h70oXTGmiPhQWq6UjBCq8Ahp88SHJiHHvXiTCqcwG8f/6WpxPsSJzLUp59tGuiJMcGPy/xck6RaD83NZTkpDmROF6gIOLNZue853m/sMnEioSdzMjkNY/9J8t5m91HntfVQv0VI/MKUw2ehfgR67pecfc5URE9txZoSOuZJph+Pcoz61ThiFB8ZgKVY4T9SJVZsj1ZQYNp1NVLAOpVrWOS54d5Ye17JhFMcTkfx73nPB4cTggiTWCf7tXqE5TbDK1HE9bOgfK+jkPjUlpVh67v0r9cJjgL0gCGLeAij0cps5Lq2Ne6lVombBYXbUrJmDhmh+YoA2HSmBNBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
